.PHONY: clean All

All:
	@echo "----------Building project:[ LogX_Modules - Release ]----------"
	@cd "LogX_Modules" && "$(MAKE)" -f  "LogX_Modules.mk"
clean:
	@echo "----------Cleaning project:[ LogX_Modules - Release ]----------"
	@cd "LogX_Modules" && "$(MAKE)" -f  "LogX_Modules.mk" clean
